package com.danielpm1982.vaccinesRecord.config;
import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;

public class MySecurityWebApplicationInitializer extends AbstractSecurityWebApplicationInitializer {
}
